import numpy as np
import warp as wp

X, Y, Z = 350, 350, 350
SPRAY_COUNT = 1000
S = 9
BALL_COUNT = 257  # for S=9
BACKTRACK_COUNT = 10
H = wp.float32(0.005)
TC = wp.float16(50.0)
LINEAR_SPACING = wp.float32(0.002)  # m
K = 300
DROPLET_MASS = 1.0 / 2.0
SPRAY_VELOCITY = 20.0
SPEED_DISTRIBUTION = wp.array(np.abs(np.random.normal(SPRAY_VELOCITY, SPRAY_VELOCITY / 20.0, K)), dtype=wp.float32)
SIGMA = 1.0
DT = 0.05
DRIP_VEL = 5
DRIP_AMOUNT = 1.0
L = 5
REBOUND_SPEED_DISTRIBUTION = wp.array(
    np.abs(np.random.normal(SPRAY_VELOCITY / 50.0, SPRAY_VELOCITY / 2000.0, K)), dtype=wp.float32
)
RESPREADING_BACKTRACKING_AMOUNT = 25
REBOUND_OPENING_ANGLE = wp.float32(0.7)
RENDERING_THRESHOLD = 0.5

DRIP = True
SOLIDIFY = True
REBOUND = True
REDISTRIBUTION = True
RESPREADING = True
ADHESION_CHECK = True
SPRAY = True
